### ISSUE TITLE
each_with_index vs each.with_index

### ISSUE THREAD

**Issue by tripscripts** [learn-co-curriculum/cartoon-collections#18]
so.. I used each_with_index per the instructions, but it is not valid

however, each.with_index is valid

this is highly confusing

**Comment by SophieDeBenedetto** [comment]
hi @tripscripts, there are two ways to solve this one. 

```ruby
collection.each_with_index do |element, i|
  puts "#{i + 1}: #{element}
end
```

or 

```ruby
collection.each.with_index(1) do |element, i|
  puts "#{i}: #{element}
end
```

`each_with_index` doesn't take in any arguments, but does yield the index number to the block, starting at index 0. So, you can get a human-friendly count by increment that index by 1 so that the count appears to start at 1 and go up from there. Or you can use `#each.with_index` and give it an argument of the number to offset the index number by. 

the ruby documentation that we link to in this readme goes over this so i'm going to close this issue.

**Comment by tripscripts** [comment]
@SophieDeBenedetto I appreciate you following up. I got this example to work after adding end quotes.

The documentation example is what confused me, and is why I referred to the solution set.

Thanks again.
